import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "user dashboard",
  description: "Generated by create next app",
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body className={`antialiased`}>
      <Navbar />

      <div className="flex justify-center gap-16 items-start">
        <div className="  mt-[75px] fixed left-0">
          <Sidebar />
        </div>
        <div className="w-[70%] ">{children}</div>
      </div>
    </body>
  );
}
