import type { Metadata } from "next";
import { Providers } from "../lib/Providers";

import "./globals.css";
import ScrollToTop from "@/components/scrollToTop/ScrollToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
        <ScrollToTop />
      </body>
    </html>
  );
}
